
const actionTypes = {
  STORE_GAMES_DATA: 'STORE_GAMES_DATA',
  UPDATE_CURRENT_SCREEN: 'UPDATE_CURRENT_SCREEN',
  SHOW_GAMGES_DATA: 'SHOW_GAMGES_DATA',
  CARDS_PER_SCREEN: 'CARDS_PER_SCREEN',
  SET_SORT_KEY: 'SET_SORT_KEY',
  SET_SORT_ORDER: 'SET_SORT_ORDER',
  SET_SEARCH_STRING: 'SET_SEARCH_STRING'
};

export default actionTypes;